#!/usr/bin/env bash
# init.sh -- bootstrap company state at ~/.software-house/
# Spec: operations/init.md | Tier 2 (additive)

op_init() {
  local harnesses=()
  local dirs_to_create=()
  local files_to_create=()

  # Step 1: Detect existing state
  if [[ -f "$COMPANY_INDEX" ]]; then
    printf 'Company already initialized at %s. Run /software-house list instead.\n' "$SH_HOME"
    return 0
  fi

  # Step 2: Detect installed harnesses
  detect_harnesses

  local harness_list=()
  (( HAS_CLAUDE_CODE )) && harness_list+=("claude-code")
  (( HAS_CODEX )) && harness_list+=("codex")
  (( HAS_GEMINI )) && harness_list+=("gemini")

  if (( ${#harness_list[@]} == 0 )); then
    printf 'Warning: no agent CLI detected. Company state will be created but no harness adapters will be writable.\n'
  else
    printf 'Detected harnesses: %s\n' "${harness_list[*]}"
  fi

  # Step 3: Compute the plan
  dirs_to_create=(
    "$SH_HOME"
    "$COMPANY_HOME"
    "$COMPANY_HOME/raw"
    "$COMPANY_HOME/wiki"
    "$COMPANY_HOME/wiki/people"
    "$COMPANY_HOME/wiki/teams"
    "$COMPANY_HOME/wiki/departments"
    "$COMPANY_HOME/wiki/synthesis"
    "$COMPANY_HOME/policies"
    "$COMPANY_HOME/alumni"
    "$COMPANY_HOME/outsource"
    "$DEPARTMENTS_HOME"
    "$AGENTS_GLOBAL"
    "$CONFIG_HOME"
  )

  files_to_create=(
    "$COMPANY_HOME/CLAUDE.md"
    "$COMPANY_INDEX"
    "$AUDIT_LOG"
    "$OUTSOURCE_MANIFEST"
    "$PROJECTS_INDEX"
    "$PROVIDERS_CONFIG"
    "$MODELS_CONFIG"
  )

  # Step 4: Tier-2 confirmation
  printf '\nI will create the following:\n'
  printf '  Directories:\n'
  for d in "${dirs_to_create[@]}"; do
    [[ -d "$d" ]] || printf '    %s\n' "$d"
  done
  printf '  Files:\n'
  for f in "${files_to_create[@]}"; do
    [[ -f "$f" ]] || printf '    %s\n' "$f"
  done

  if ! confirm 2; then
    return 1
  fi

  # Step 5-6: Create directories and files
  if dry_run_msg "Would create directories and files"; then
    return 0
  fi

  # Create directories
  for d in "${dirs_to_create[@]}"; do
    if [[ ! -d "$d" ]]; then
      mkdir -p "$d" || { log_error "Failed to create directory: $d"; return 1; }
    fi
  done

  local utc_ts
  utc_ts="$(utc_now)"
  local utc_d
  utc_d="$(utc_date)"

  # Create CLAUDE.md (company schema)
  if [[ ! -f "$COMPANY_HOME/CLAUDE.md" ]]; then
    cat > "$COMPANY_HOME/CLAUDE.md" << 'COMPANYEOF'
---
type: company-schema
classification: internal
created_at: __UTC_DATE__
---

# Company Schema

This file defines how this company's state is structured. The
software-house skill maintains it. Edits here change company-wide
conventions. The same file is read by Claude Code, Codex CLI, and
Gemini CLI invocations of the skill.

## Tiers

1. Company -- this directory (~/.software-house/company/)
2. Department -- ~/.software-house/departments/<dept>/
3. Team -- <project>/.software-house/team/
4. Role -- agent files at <project>/.software-house/agents/<name>.md
   (canonical) and <project>/<harness>/agents/<name>.md (adapters);
   freelance pool at ~/.software-house/agents/<name>.md

## Wiki layout per tier

- raw/ -- immutable source documents
- wiki/ -- compiled entity, concept, synthesis pages
- index.md -- generated catalog (do not edit)
- audit.log -- generated append-only log (do not edit)

## Page types

- People (employees), Teams, Departments -- entity pages
- Concepts -- non-entity knowledge (policies, standards, decisions)
- Synthesis -- derived views (org chart, dashboards, retros)

## Classification

Every page declares one of: public | internal | confidential | restricted.
The skill enforces classification ceilings during reads.

## Provider awareness

Every employee page declares provider and egress_consent in
frontmatter. Providers are classified in
~/.software-house/config/providers.json as local (no egress) or
external (egress with typed consent). See policies/privacy.md.
COMPANYEOF
    sed -i "s/__UTC_DATE__/$utc_d/" "$COMPANY_HOME/CLAUDE.md"
  fi

  # Create index.md
  if [[ ! -f "$COMPANY_INDEX" ]]; then
    cat > "$COMPANY_INDEX" << 'INDEXEOF'
# Company Wiki Index

This index is auto-generated by the software-house skill. Do not edit
directly -- your changes will be overwritten on the next rebuild.

## People

(none yet -- run /software-house hire to add employees)

## Teams

(none yet)

## Departments

(none yet -- run /software-house dept-create to add departments)

## Synthesis

(none yet)
INDEXEOF
  fi

  # Create empty audit log
  [[ -f "$AUDIT_LOG" ]] || touch "$AUDIT_LOG"

  # Create outsource manifest
  if [[ ! -f "$OUTSOURCE_MANIFEST" ]]; then
    printf '{"freelancers":[]}\n' > "$OUTSOURCE_MANIFEST"
  fi

  # Create projects index
  if [[ ! -f "$PROJECTS_INDEX" ]]; then
    printf '{"projects":{}}\n' > "$PROJECTS_INDEX"
  fi

  # Copy default providers.json
  if [[ ! -f "$PROVIDERS_CONFIG" ]]; then
    if [[ -f "$CONFIG_SRC_DIR/providers.json" ]]; then
      cp "$CONFIG_SRC_DIR/providers.json" "$PROVIDERS_CONFIG"
    else
      log_error "Bundled providers.json not found at $CONFIG_SRC_DIR/providers.json. Skill install incomplete."
      return 1
    fi
  fi

  # Copy default models-config.json
  if [[ ! -f "$MODELS_CONFIG" ]]; then
    if [[ -f "$CONFIG_SRC_DIR/models-config.json" ]]; then
      cp "$CONFIG_SRC_DIR/models-config.json" "$MODELS_CONFIG"
    else
      # Write minimal stub
      cat > "$MODELS_CONFIG" << 'MODELSEOF'
{
  "version": 1,
  "defaults_by_role": {
    "default": {"provider": "ollama", "model": "qwen3-coder:32b", "effort": "medium"}
  },
  "effort_presets": {
    "low":    {"max_tokens": 4096,  "thinking": false, "temperature": 0.2},
    "medium": {"max_tokens": 16384, "thinking": false, "temperature": 0.3},
    "high":   {"max_tokens": 65536, "thinking": true,  "temperature": 0.5}
  },
  "model_aliases": {}
}
MODELSEOF
    fi
  fi

  # Step 7: Append audit log entry
  local harness_json
  harness_json="$(printf '%s\n' "${harness_list[@]}" | jq -R . | jq -s . 2>/dev/null || echo '[]')"
  local audit_entry
  audit_entry="{\"ts\":\"$utc_ts\",\"actor\":\"user\",\"op\":\"init\",\"scope\":\"company\",\"args\":{\"harnesses\":$harness_json},\"diff\":{\"created\":[]},\"confirmation\":{\"tier\":2},\"egress_consent\":{\"required\":false},\"result\":\"ok\"}"
  audit_log "$audit_entry"

  # Step 8: Report
  local provider_count=0
  local external_count=0
  if command -v jq &>/dev/null && [[ -f "$PROVIDERS_CONFIG" ]]; then
    provider_count="$(jq '.providers | length' "$PROVIDERS_CONFIG" 2>/dev/null || echo 0)"
    external_count="$(jq '[.providers | .[] | select(.class=="external")] | length' "$PROVIDERS_CONFIG" 2>/dev/null || echo 0)"
  fi

  local default_provider default_model default_effort
  if command -v jq &>/dev/null && [[ -f "$MODELS_CONFIG" ]]; then
    default_provider="$(jq -r '.defaults_by_role.default.provider' "$MODELS_CONFIG" 2>/dev/null || echo "ollama")"
    default_model="$(jq -r '.defaults_by_role.default.model' "$MODELS_CONFIG" 2>/dev/null || echo "unknown")"
    default_effort="$(jq -r '.defaults_by_role.default.effort' "$MODELS_CONFIG" 2>/dev/null || echo "medium")"
  else
    default_provider="ollama"
    default_model="qwen3-coder:32b"
    default_effort="medium"
  fi

  printf '\nCompany initialized at %s\n' "$SH_HOME"
  printf '  Provider config:  %s (%s providers, %s external)\n' "$PROVIDERS_CONFIG" "$provider_count" "$external_count"
  printf '  Default model:    %s:%s (effort: %s)\n' "$default_provider" "$default_model" "$default_effort"
  if (( ${#harness_list[@]} > 0 )); then
    printf '  Harness adapters: %s\n' "${harness_list[*]}"
  else
    printf '  Harness adapters: (none detected)\n'
  fi
  printf '\n  Next steps:\n'
  printf '    /software-house dept-create <name>                       create a department\n'
  printf '    /software-house hire <name> --role <r>                   hire your first employee\n'
  printf '    /software-house list                                     show what is in the company\n'
}